### ISSUE TITLE
Add a screenshot in the README.md

### ISSUE THREAD

**Issue by ashwani99** [ashwani99/rock-paper-scissors#1]

**Comment by nicolaspascual** [comment]
Already done!! :smile:

**Comment by jxom** [comment]
Hahaha oops :P

**Comment by ashwani99** [comment]
@jxom I like the gif. Can it be made little more smooth with the whole screen? And put the gif in the repo itself inside an `assets` folder?

**Comment by ashwani99** [comment]
Closed via 9e3c1efc8a52cb756b662295fc156f3e363da748 and 2746e6b990ee43c4e4e3ebe2545e13a9c3ee5436
